#pragma config(Sensor, in1,    Gyro,                sensorGyro)
#pragma config(Sensor, dgtl1,  LDriveEncoder,       sensorRotation)
#pragma config(Sensor, dgtl2,  RDriveEncoder,       sensorRotation)
#pragma config(Sensor, dgtl3,  LiftEncoder,         sensorRotation)
#pragma config(Sensor, dgtl4,  LiftTrigger,         sensorTouch)
#pragma config(Motor,  port1,           IntakeL,       tmotorNormal, openLoop)
#pragma config(Motor,  port2,           IntakeR,       tmotorNormal, openLoop)
#pragma config(Motor,  port3,           LDrive1,       tmotorNormal, openLoop)
#pragma config(Motor,  port4,           LDrive2,       tmotorNormal, openLoop)
#pragma config(Motor,  port5,           RDrive1,       tmotorNormal, openLoop)
#pragma config(Motor,  port6,           RDrive2,       tmotorNormal, openLoop)
#pragma config(Motor,  port7,           LLift,         tmotorNormal, openLoop)
#pragma config(Motor,  port8,           RLift,         tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

//state flags

//functions
//programmers, flesh these out w/ your current knowledge
//rely on info from the tutorials for this
void setDrive(int lpwm, int rpwm);
void setLift(int pwm);
void clearEncoders();

void pre_auton()
{
	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

task autonomous()
{

	AuonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{
	  UserControlCodePlaceholderForTesting(); // Remove this function call once you have "real" code.
	}
}
